windowrule {
  name = steam-discord-login

  match {
    initial_title = Sign in to Steam|Discord Updater
  }

  float = true
  
  opacity = 0.45

  move = (monitor_w-window_w-16) (monitor_h-window_h-16)
}

windowrule {
  name = discord-steam-workspace

  match {
    class = discord|steam
    initial_class = discord|steam
  }

  opacity = 0.95
  workspace = 9
}
