windowrule {
  name = steam-discord-login

  match {
    class         = steam|discord
    initial_title = Sign in to Steam|Discord Updater
  }

  float = true
  
  opacity = 0.45

  move = (monitor_w-window_w-16) (monitor_h-window_h-16)
}

windowrule {
  name = feishin-transparent

  match {
    initial_class = feishin
  }

  opacity = 0.95
}
